image: docker:18.09.6-git

variables:
  DOCKER_DRIVER: overlay2
  GIT_STRATEGY: fetch
  GIT_DEPTH: "3"

before_script:
  - source ci-utils.sh

stages:
  - build
  - deploy

build:
  stage: build
  services:
    - docker:18.09.6-dind
  variables:
    DOCKER_HOST: tcp://docker:2375/
  script:
    - build ${CI_COMMIT_REF_SLUG}

staging:
  stage: deploy
  script:
    - deploy root rubycrm-ssh.gelonos.com
  only:
    - develop

production:
  stage: deploy
  script:
    - deploy root rubycrm-ssh.gelonos.com
  only:
    - master
